name = "domainspec"
defaultTargets = ["DomainSpec", "Fractal", "FractalOP", "M6Counter", "M2Counter", "Cofractal", "CounitCounter", "S3Fractal", "S2VsS3Counter"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "DomainSpec"
srcDir = ".."

[[lean_lib]]
name = "Fractal"
srcDir = ".."

[[lean_lib]]
name = "FractalOP"
srcDir = ".."

[[lean_lib]]
name = "M6Counter"
srcDir = ".."

[[lean_lib]]
name = "M2Counter"
srcDir = ".."

[[lean_lib]]
name = "Cofractal"
srcDir = ".."

[[lean_lib]]
name = "CounitCounter"
srcDir = ".."

[[lean_lib]]
name = "S3Fractal"
srcDir = ".."

[[lean_lib]]
name = "S2VsS3Counter"
srcDir = ".."
