/-
Copyright (c) 2026 Victor Boscaro. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Victor Boscaro

# IAI-2: the bicyclic refutation (mono direction)

The strong witness for the mono half of the iso/mono asymmetry. There
exists a faithful functor `Δ : BM ⥤ BN` between one-object categories, a
non-trivial left `ℕ`-act `X = {0, 1, ⋆}` (the "torsion act"), and an
explicit equality `(ι_{(*, 1)}) 0 = (ι_{(*, 1)}) 1` in the colimit
`(Lan_Δ X)(c)`, driven by a relation `a · b = 1` in `BN`. Hence the
canonical Lan-adjunction unit at `X`, evaluated at the unique object of
`BM`, is **not** injective, hence not monic in `Type`.

This is the project's strongest schema-side-faithful / instance-side-leaky
witness — strictly stronger than `M6Counter`, which only refutes the
*iso* direction. Per the round-4 draft W1 §3.5a, the mechanism is an
intra-fibre cancellation driven by a relation `a · b = 1` between two
morphisms of `L₂`, invisible to `L₁`.

## Construction (modulus: use `Function.End ℕ` for the target)

The mathematical statement asks for the bicyclic monoid
`B = ⟨a, b | a b = 1⟩` as `L₂`. The crucial property of `B` used in the
collapse argument is *only* that it contains an element `a` and the
image of `b ∈ ι(M)` satisfying `a · b = 1`. Constructing `B` from
generators-and-relations in Lean is heavy; instead we take

  `L₂ := B(Function.End ℕ)`,  with  `bFn := Nat.succ`,  `aFn := n ↦ n - 1`,

inside which `aFn * bFn = 1` (truncated predecessor is a *left* inverse
to successor; in `Function.End ℕ`, `(f * g) n = f (g n)`). The embedding
`ι : ℕ → Function.End ℕ` is `n ↦ bFn^n`, faithful because
`bFn^n = bFn^m → n = m` (apply both sides to `0`).

The submonoid of `Function.End ℕ` generated by `aFn`, `bFn` is precisely
the bicyclic monoid (standard fact; see e.g. Clifford-Preston), but we
do not need this isomorphism: we only need a target monoid containing
the relation `a·b = 1`.

## The torsion left ℕ-act

`X = ULift Bool ⊕ ULift PUnit`, identifying:
* `0 = Sum.inl ⟨false⟩`,
* `1 = Sum.inl ⟨true⟩`,
* `⋆ = Sum.inr ⟨⟩`,

with action `0 · x = x` and `n · x = ⋆` for `n ≥ 1`.

## Closure mark

`closed-proof` for the entire construction:
* `Function.End ℕ` as a monoid containing the bicyclic relation
  (`aFn_mul_bFn`),
* the faithful monoid hom `ι : Multiplicative ℕ →* Function.End ℕ` and
  the resulting faithful functor `Δ : BM ⥤ BN` between one-object cats,
* the torsion `Multiplicative ℕ`-act `X` as a functor `BM ⥤ Type`,
* the **load-bearing collapse equation** `colimit.ι _ obj1 0 =
  colimit.ι _ obj1 1` via `colimit.w` along the morphism
  `(*, 1) → (*, aFn)` labeled `f = 1` in `Δ/c`,
* the headline theorem `lanUnit_app_not_mono_bicyclic`:
  `¬ Mono (((Δ.lanAdjunction _).unit.app X).app ⟨⟩)`.
-/

import Mathlib.CategoryTheory.Functor.KanExtension.Adjunction
import Mathlib.CategoryTheory.Limits.Types.Colimits
import Mathlib.CategoryTheory.Types.Basic
import Mathlib.CategoryTheory.SingleObj
import Mathlib.CategoryTheory.Comma.StructuredArrow.Small
import Mathlib.Algebra.Group.End
import Mathlib.Algebra.Group.TypeTags.Basic
import Mathlib.Algebra.Group.Nat.Hom

open CategoryTheory Functor Limits

set_option maxHeartbeats 800000

namespace Bicyclic

/-! ## The bicyclic relation inside `Function.End ℕ`. -/

/-- Truncated predecessor. -/
def aFn : Function.End ℕ := fun n => n - 1

/-- Successor. -/
def bFn : Function.End ℕ := Nat.succ

/-- The bicyclic relation `a · b = 1` realised inside `Function.End ℕ`
under the convention `(f * g) n = f (g n)`. -/
lemma aFn_mul_bFn : aFn * bFn = 1 := by
  funext n
  show aFn (bFn n) = n
  simp [aFn, bFn]

/-- `bFn^n` acts as `+n` on `ℕ`. -/
lemma bFn_pow_apply (n : ℕ) : ∀ m : ℕ, (bFn ^ n) m = m + n := by
  induction n with
  | zero =>
      intro m
      show (1 : Function.End ℕ) m = m + 0
      change m = m + 0
      omega
  | succ k ih =>
      intro m
      have h : bFn ^ (k + 1) = bFn ^ k * bFn := pow_succ _ _
      rw [h]
      show (bFn ^ k) (bFn m) = m + (k + 1)
      rw [ih (bFn m)]
      show bFn m + k = m + (k + 1)
      show (m + 1) + k = m + (k + 1)
      omega

/-- `bFn^n` applied to `0` is `n`. -/
lemma bFn_pow_apply_zero (n : ℕ) : (bFn ^ n) (0 : ℕ) = n := by
  rw [bFn_pow_apply]; simp

/-- The map `n ↦ bFn^n` from `(ℕ, +)` is injective. -/
lemma bFn_pow_injective : Function.Injective (fun n : ℕ => bFn ^ n) := by
  intro n m h
  have h0 := congrArg (fun (f : Function.End ℕ) => f 0) h
  simp [bFn_pow_apply_zero] at h0
  exact h0

/-! ## The faithful monoid homomorphism `ι : Multiplicative ℕ →* Function.End ℕ`. -/

/-- `ι(n) = bFn^n`. As a monoid hom `Multiplicative ℕ →* Function.End ℕ`
via Mathlib's `powersHom`. -/
def ιHom : Multiplicative ℕ →* Function.End ℕ := powersHom _ bFn

@[simp] lemma ιHom_apply (n : Multiplicative ℕ) :
    ιHom n = bFn ^ n.toAdd := rfl

lemma ιHom_injective : Function.Injective ιHom := by
  intro n m h
  have hpow : bFn ^ n.toAdd = bFn ^ m.toAdd := h
  have h2 : n.toAdd = m.toAdd := bFn_pow_injective hpow
  exact Multiplicative.toAdd.injective h2

/-! ## One-object categories and `Δ`. -/

/-- `BM := SingleObj (Multiplicative ℕ)` — the schema-side one-object
category. -/
abbrev BM : Type := SingleObj (Multiplicative ℕ)

/-- `BN := SingleObj (Function.End ℕ)` — the instance-side one-object
category, with the bicyclic relation `aFn * bFn = 1` in its hom-monoid. -/
abbrev BN : Type := SingleObj (Function.End ℕ)

/-- `Δ : BM ⥤ BN` induced by `ιHom`. -/
def Δ : BM ⥤ BN := SingleObj.mapHom (Multiplicative ℕ) (Function.End ℕ) ιHom

/-- `Δ` is faithful: `Δ.map f = Δ.map g ↔ ιHom f = ιHom g ↔ f = g`. -/
instance : Δ.Faithful where
  map_injective h := ιHom_injective h

/-! ## The torsion left `ℕ`-act `X = {0, 1, ⋆}`. -/

/-- Underlying type of the torsion act: three elements `zero`, `one`,
`star`. -/
inductive XCarrier : Type
  | zero
  | one
  | star
  deriving DecidableEq

namespace XCarrier

/-- Action of `n : ℕ`: `0` acts as identity, every `n ≥ 1` collapses
everything to `star`. -/
def act (n : ℕ) (x : XCarrier) : XCarrier :=
  match n with
  | 0 => x
  | _ + 1 => XCarrier.star

@[simp] lemma act_zero (x : XCarrier) : act 0 x = x := rfl

@[simp] lemma act_succ (n : ℕ) (x : XCarrier) : act (n + 1) x = star := rfl

lemma act_pos {n : ℕ} (hn : 0 < n) (x : XCarrier) : act n x = star := by
  cases n with
  | zero => exact absurd hn (lt_irrefl _)
  | succ k => rfl

/-- Associativity of the action: `act (n + m) x = act n (act m x)`. -/
lemma act_add (n m : ℕ) (x : XCarrier) :
    act (n + m) x = act n (act m x) := by
  rcases Nat.eq_zero_or_pos n with hn | hn
  · subst hn; simp
  · rcases Nat.eq_zero_or_pos m with hm | hm
    · subst hm; simp [act_pos hn]
    · have hnm : 0 < n + m := Nat.add_pos_left hn _
      rw [act_pos hnm, act_pos hm, act_pos hn]

end XCarrier

/-- The torsion act as a functor `BM ⥤ Type`. The unique object of `BM`
goes to `XCarrier`; each morphism `n : Multiplicative ℕ` acts via
`XCarrier.act n.toAdd`. -/
def X : BM ⥤ Type where
  obj _ := XCarrier
  map {_ _} n := TypeCat.ofHom (XCarrier.act n.toAdd)
  map_id _ := by
    apply ConcreteCategory.hom_ext
    intro x
    show XCarrier.act (1 : Multiplicative ℕ).toAdd x = x
    rfl
  map_comp := by
    rintro ⟨⟩ ⟨⟩ ⟨⟩ (n : Multiplicative ℕ) (m : Multiplicative ℕ)
    apply ConcreteCategory.hom_ext
    intro x
    -- In `SingleObj M`, `n ≫ m = m * n` definitionally, and hom = M.
    show XCarrier.act ((m * n : Multiplicative ℕ).toAdd) x
         = XCarrier.act m.toAdd (XCarrier.act n.toAdd x)
    have h2 : (m * n : Multiplicative ℕ).toAdd = m.toAdd + n.toAdd := rfl
    rw [h2, XCarrier.act_add]

/-! ## The collapse: the Lan-unit at `X` is not monic.

Plan:
* Note `Δ.HasPointwiseLeftKanExtension X` (Mathlib gives this once
  smallness holds for the comma category, which holds since `BM`, `BN`
  are small).
* Use `Δ.leftKanExtensionObjIsoColimit X (SingleObj.star _)` to identify
  `(Δ.lan.obj X).obj *` with `colimit (CostructuredArrow.proj Δ * ⋙ X)`.
* Construct two objects `obj1`, `objA` in `CostructuredArrow Δ (SingleObj.star _)`
  corresponding to `h = 1_N` and `h = aFn`.
* Construct a morphism `obj1 ⟶ objA` from `f = 1 ∈ Multiplicative ℕ`,
  whose existence rests on `aFn * bFn = 1` (i.e. `aFn_mul_bFn`).
* Apply `colimit.w` to conclude `(ι _ obj1) ∘ (X.map f) = (ι _ objA)`.
* Evaluate at `XCarrier.zero` vs `XCarrier.one`: both go via
  `X.map f = act 1 = const star` to the same image in the colimit.
* Conclude the Lan-unit component is not injective. -/

/-- The object `(*, 1_N) : CostructuredArrow Δ *`. -/
def obj1 : CostructuredArrow Δ (SingleObj.star (Function.End ℕ)) :=
  CostructuredArrow.mk (Y := SingleObj.star _)
    ((1 : Function.End ℕ) :
      Δ.obj (SingleObj.star _) ⟶ SingleObj.star (Function.End ℕ))

/-- The object `(*, aFn) : CostructuredArrow Δ *`. -/
def objA : CostructuredArrow Δ (SingleObj.star (Function.End ℕ)) :=
  CostructuredArrow.mk (Y := SingleObj.star _)
    (aFn : Δ.obj (SingleObj.star _) ⟶ SingleObj.star (Function.End ℕ))

/-- The morphism `obj1 ⟶ objA` in the comma category, labeled by
`f = (1 : ℕ)` viewed as element of `Multiplicative ℕ` (i.e.
`Multiplicative.ofAdd 1`). Existence rests on `aFn ∘ bFn = id`. -/
def arrow1ToA : obj1 ⟶ objA := by
  refine CostructuredArrow.homMk
    (f := obj1) (f' := objA)
    (show (obj1.left ⟶ objA.left) from (Multiplicative.ofAdd 1 : Multiplicative ℕ))
    ?_
  -- Goal: `Δ.map (ofAdd 1) ≫ objA.hom = obj1.hom`.
  -- i.e. `Δ.map (ofAdd 1) ≫ aFn = 1` in `BN`.
  -- Composition in `SingleObj`: `f ≫ g = g * f`. `Δ.map (ofAdd 1) = bFn`.
  show (Δ.map ((Multiplicative.ofAdd 1 : Multiplicative ℕ) :
              SingleObj.star _ ⟶ SingleObj.star _) ≫
        (aFn : SingleObj.star _ ⟶ SingleObj.star _))
       = ((1 : Function.End ℕ) : SingleObj.star _ ⟶ SingleObj.star _)
  -- In `SingleObj M`, `f ≫ g = g * f`, hom = M.
  change (aFn * Δ.map ((Multiplicative.ofAdd 1 : Multiplicative ℕ) :
                       SingleObj.star (Multiplicative ℕ) ⟶
                       SingleObj.star (Multiplicative ℕ))
            : Function.End ℕ) = 1
  have hδ : @CategoryTheory.Functor.map BM _ BN _ Δ (SingleObj.star _) (SingleObj.star _)
              (Multiplicative.ofAdd 1) = bFn := by
    show ιHom (Multiplicative.ofAdd 1) = bFn
    simp [ιHom_apply]
  -- The goal already has `Δ.map (ofAdd 1)` instead of `bFn`; just check
  -- they're equal directly.
  show aFn * Δ.map ((Multiplicative.ofAdd 1 : Multiplicative ℕ) :
      SingleObj.star (Multiplicative ℕ) ⟶ SingleObj.star (Multiplicative ℕ)) = 1
  rw [show (Δ.map ((Multiplicative.ofAdd 1 : Multiplicative ℕ) :
      SingleObj.star (Multiplicative ℕ) ⟶ SingleObj.star (Multiplicative ℕ)))
        = bFn from rfl]
  exact aFn_mul_bFn

/-! ## Smallness and pointwise Kan extension. -/

instance : Small.{0} BM := small_self _
instance : Small.{0} BN := small_self _

instance : LocallySmall.{0} BN where
  hom_small _ _ := small_self _

/-- Mathlib provides `HasPointwiseLeftKanExtension` once the relevant
comma category has a colimit in `Type 0`. -/
instance (Y : BM ⥤ Type) : Δ.HasPointwiseLeftKanExtension Y :=
  fun _ => inferInstance

/-! ## The headline collapse equation in the colimit.

`(ι _ obj1) ∘ (X.map (ofAdd 1)) = (ι _ objA)` by `colimit.w` along
`arrow1ToA`. Evaluating at `XCarrier.zero` and `XCarrier.one`, both sides
of `X.map (ofAdd 1)` collapse to `XCarrier.star`, so they share an image
in the colimit. -/

/-- Notation alias for the comma-category-indexed diagram into `Type`. -/
abbrev colimDiagram :
    CostructuredArrow Δ (SingleObj.star (Function.End ℕ)) ⥤ Type :=
  CostructuredArrow.proj Δ (SingleObj.star (Function.End ℕ)) ⋙ X

/-- The colimit-collapse identity: `0` and `1` are identified at `obj1`
in the colimit, via the arrow `arrow1ToA`. -/
lemma colimit_ι_obj1_zero_eq_one :
    colimit.ι colimDiagram obj1 XCarrier.zero
      = colimit.ι colimDiagram obj1 XCarrier.one := by
  -- By `colimit.w arrow1ToA`:
  --   `colimDiagram.map arrow1ToA ≫ colimit.ι _ objA = colimit.ι _ obj1`.
  -- The map `colimDiagram.map arrow1ToA = X.map (ofAdd 1) = act 1`,
  -- which sends both `zero` and `one` to `star`. So:
  --   `colimit.ι _ obj1 zero = colimit.ι _ objA star = colimit.ι _ obj1 one`.
  have hw := colimit.w colimDiagram arrow1ToA
  -- Apply `hw` evaluated at `zero` and `one`. Use `congr_fun` form on
  -- the underlying function via `ConcreteCategory.hom_ext`-style
  -- evaluation.
  have hzero :
      colimit.ι colimDiagram objA
        ((colimDiagram.map arrow1ToA) XCarrier.zero)
      = colimit.ι colimDiagram obj1 XCarrier.zero := by
    exact congrArg (fun f => f XCarrier.zero)
      (congrArg ConcreteCategory.hom hw)
  have hone :
      colimit.ι colimDiagram objA
        ((colimDiagram.map arrow1ToA) XCarrier.one)
      = colimit.ι colimDiagram obj1 XCarrier.one := by
    exact congrArg (fun f => f XCarrier.one)
      (congrArg ConcreteCategory.hom hw)
  -- Both `colimDiagram.map arrow1ToA` images equal `star`.
  have hev_zero : (colimDiagram.map arrow1ToA) XCarrier.zero = XCarrier.star := rfl
  have hev_one  : (colimDiagram.map arrow1ToA) XCarrier.one  = XCarrier.star := rfl
  rw [hev_zero] at hzero
  rw [hev_one] at hone
  exact hzero.symm.trans hone

/-! ## Main theorem: the Lan-unit at `X` is not monic.

We extract bijection-failure from the colimit identification: the
unit's component at the unique object of `BM` factors through
`colimit … ≅ (Δ.lan.obj X).obj (SingleObj.star _)`, and the
identification produced by `colimit_ι_obj1_zero_eq_one` lives in the
codomain. Hence two distinct elements of `XCarrier` map to the same
element of `(Δ.lan.obj X).obj …`, so the unit's component is not
injective, hence not monic in `Type`. -/

/-- Note: `obj1 = CostructuredArrow.mk (𝟙 _)` definitionally because in
`SingleObj M`, `𝟙 ⋆ = 1`. This is recorded as a `rfl` lemma. -/
lemma obj1_eq_mk_id :
    obj1 = CostructuredArrow.mk
      (𝟙 (Δ.obj (SingleObj.star (Multiplicative ℕ)))) := rfl

/-- The Lan-unit at `X`, evaluated at the unique object of `BM` and at
`x : XCarrier`, is identified (via the canonical
`leftKanExtensionObjIsoColimit` iso) with the colimit injection
`colimit.ι _ obj1 x`. -/
lemma iso_hom_apply_unit_eq_colim_ι (x : XCarrier) :
    (Δ.leftKanExtensionObjIsoColimit X
        (SingleObj.star (Function.End ℕ))).hom
      ((((Δ.lanAdjunction Type).unit.app X).app
          (SingleObj.star (Multiplicative ℕ))) x)
      = colimit.ι colimDiagram obj1 x := by
  -- Identify `(Δ.lanAdjunction Type).unit = Δ.lanUnit`.
  have hunit :
      ((Δ.lanAdjunction Type).unit.app X).app (SingleObj.star _)
      = (Δ.lanUnit.app X).app (SingleObj.star _) := by
    rw [lanAdjunction_unit]
  rw [hunit]
  -- `lanUnit.app X = leftKanExtensionUnit Δ X` (definitionally).
  -- Apply Mathlib's `leftKanExtensionUnit_leftKanExtensionObjIsoColimit_hom`:
  --   `(leftKanExtensionUnit Δ X).app star ≫ iso.hom =
  --      colimit.ι _ (CostructuredArrow.mk (𝟙 _))`.
  have hcomp := Δ.leftKanExtensionUnit_leftKanExtensionObjIsoColimit_hom
    (F := X) (X := SingleObj.star (Multiplicative ℕ))
  -- `hcomp` says exactly that the composite of the two maps equals
  -- `colimit.ι _ obj1` (modulo the `obj1 = CostructuredArrow.mk (𝟙 _)`
  -- identification). Evaluate both sides at `x`.
  have happ := congrArg (fun f => (ConcreteCategory.hom f) x) hcomp
  -- `happ : (iso.hom ∘ unit-app) x = colimit.ι _ (CostructuredArrow.mk (𝟙 _)) x`
  -- Unfold the composition on the LHS.
  show (Δ.leftKanExtensionObjIsoColimit X (SingleObj.star (Function.End ℕ))).hom
        (((Δ.lanUnit.app X).app (SingleObj.star (Multiplicative ℕ))) x) =
       colimit.ι colimDiagram obj1 x
  -- `Δ.lanUnit.app X = Δ.leftKanExtensionUnit X` by definition.
  exact happ

/-- **Main theorem: the Lan-unit at `X` is not injective.** Two distinct
elements of `XCarrier` map to the same element of
`(Δ.lan.obj X).obj (SingleObj.star _)`. -/
theorem lanUnit_app_not_injective_bicyclic :
    ¬ Function.Injective
        ((((Δ.lanAdjunction Type).unit.app X).app
            (SingleObj.star (Multiplicative ℕ))) :
          XCarrier → _) := by
  intro hinj
  -- From `colimit_ι_obj1_zero_eq_one`, the colimit injections agree.
  have hcolim := colimit_ι_obj1_zero_eq_one
  -- Pull back through the iso to the unit's codomain.
  have hzero := iso_hom_apply_unit_eq_colim_ι XCarrier.zero
  have hone  := iso_hom_apply_unit_eq_colim_ι XCarrier.one
  -- Combine: `iso.hom (unit zero) = iso.hom (unit one)`.
  have hiso_eq :
      (Δ.leftKanExtensionObjIsoColimit X
        (SingleObj.star (Function.End ℕ))).hom
        ((((Δ.lanAdjunction Type).unit.app X).app
            (SingleObj.star (Multiplicative ℕ))) XCarrier.zero)
      = (Δ.leftKanExtensionObjIsoColimit X
        (SingleObj.star (Function.End ℕ))).hom
        ((((Δ.lanAdjunction Type).unit.app X).app
            (SingleObj.star (Multiplicative ℕ))) XCarrier.one) := by
    rw [hzero, hone]; exact hcolim
  -- An iso in `Type` is bijective on underlying sets; apply its inverse.
  have hunit_eq :
      (((Δ.lanAdjunction Type).unit.app X).app
          (SingleObj.star (Multiplicative ℕ))) XCarrier.zero
      = (((Δ.lanAdjunction Type).unit.app X).app
          (SingleObj.star (Multiplicative ℕ))) XCarrier.one := by
    -- Use `Iso.toEquiv` injectivity to lift `hiso_eq` back to the unit.
    have hinj_iso : Function.Injective
      (ConcreteCategory.hom
        (Δ.leftKanExtensionObjIsoColimit X (SingleObj.star (Function.End ℕ))).hom) := by
      intro a b h
      have hab :
          (Δ.leftKanExtensionObjIsoColimit X (SingleObj.star (Function.End ℕ))).inv
            ((Δ.leftKanExtensionObjIsoColimit X (SingleObj.star (Function.End ℕ))).hom a)
          = (Δ.leftKanExtensionObjIsoColimit X (SingleObj.star (Function.End ℕ))).inv
            ((Δ.leftKanExtensionObjIsoColimit X (SingleObj.star (Function.End ℕ))).hom b) := by
        change (ConcreteCategory.hom
          (Δ.leftKanExtensionObjIsoColimit X (SingleObj.star (Function.End ℕ))).inv)
          ((ConcreteCategory.hom
            (Δ.leftKanExtensionObjIsoColimit X (SingleObj.star (Function.End ℕ))).hom) a)
          = (ConcreteCategory.hom
              (Δ.leftKanExtensionObjIsoColimit X (SingleObj.star (Function.End ℕ))).inv)
            ((ConcreteCategory.hom
              (Δ.leftKanExtensionObjIsoColimit X (SingleObj.star (Function.End ℕ))).hom) b)
        exact congrArg _ h
      simpa [Iso.hom_inv_id_apply] using hab
    exact hinj_iso hiso_eq
  -- `hinj` says the unit-app is injective; combined with `hunit_eq` gives
  -- `zero = one`, contradiction.
  exact XCarrier.noConfusion (hinj hunit_eq)

/-- **Corollary: the Lan-unit at `X` is not monic.** Since `Type` has
`mono = injective`, this is just a re-packaging of
`lanUnit_app_not_injective_bicyclic`. -/
theorem lanUnit_app_not_mono_bicyclic :
    ¬ Mono ((((Δ.lanAdjunction Type).unit.app X).app
              (SingleObj.star (Multiplicative ℕ)))) := by
  rw [CategoryTheory.mono_iff_injective]
  exact lanUnit_app_not_injective_bicyclic

end Bicyclic
